services:
    myservice:
        build:
            # filepath to the Dockerfile
            context: .
            ssh:
                # for ssh agent forwarding during build (used for cloning private git repos)
                - default
        environment:
            # for ssh agent forwarding when entering the container
            # - This is done automatically by VSC, but when working via CLI this setting is required
            SSH_AUTH_SOCK: ${SSH_AUTH_SOCK}
            # Display for GUI applications
            # - for native linux "DISPLAY: ${DISPLAY}" works
            # - for wls2 the display variable is shadowed, making the hardcoded "DISPLAY: :0" necessary
            DISPLAY: :0
            # for software rendering of opengl. Fixes errors in rqt and rviz
            LIBGL_ALWAYS_SOFTWARE: 1
        image: ${COMPOSE_PROJECT_NAME}_image
        container_name: ${COMPOSE_PROJECT_NAME}_container
        # for X11 forwarding
        network_mode: "host"
        # this command will hold the container open
        command: ["tail","-f","/dev/null"]
        volumes:
            # for ssh agent forwarding when entering the container
            # This is done automatically by VSC, but when working via CLI this setting is required
            - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
            # local mounts
            - ../catkin-ws-src_bind-mount:/home/myuser/catkin_ws/src
            - ./config_bind-mount:/config_bind-mount